
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r project-04-mlops-cicd-pipeline/requirements.txt

    - name: Run model test
      run: |
        echo "✅ Model and API structure looks good!"
        ls project-04-mlops-cicd-pipeline/

